version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    container_name: dex-price-redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - TZ=UTC
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M

volumes:
  redis_data:
    driver: local
